apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: "*"
    helm:
      values: |
        loki:
          persistence:
            enabled: false
        promtail:
          enabled: true
        grafana:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status
    - group: apps
      kind: ReplicaSet
      jsonPointers:
        - /status
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /status
        - /spec/volumeClaimTemplates/0/status
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
